# Use the official Node.js LTS image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy only package.json and package-lock.json to leverage Docker cache for dependencies
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application files
COPY . .

# Expose the port your application runs on (default is 5000 for Express apps)
EXPOSE 5001

# Define environment variables for production
ENV NODE_ENV=production

# Command to start the app
CMD ["npm", "start"]
